### ISSUE TITLE
Clicking date/time stamps on Activity Page doesn't bring up annotation card

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#102]
**Describe the bug**
When clicking on an annotation's time stamp on the Activity Page, you are brought to a blank page instead of a page with the Annotation Card.

**To Reproduce**
1. Go to your Activity Page
2. Click on a time stamp
3. Confirm you do not see the Card.

**Expected behavior**
When clicking on the time stamp, you should be brought to the Annotation Card, with the ability to delete annotations among other features.

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/79129965-26de4280-7d74-11ea-9419-fa35f422786f.png)

**Desktop (please complete the following information):**
 - Maco Mojave 10
- Chrome 81

**Comment by judell** [comment]
Error: [$injector:unpr] Unknown provider: apiProvider <- api
