### ISSUE TITLE
Sidebar loads continuously when shared Reply references an annotation that no longer exists

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#103]
**Describe the bug**
On https://www.washingtonpost.com/politics/2020/04/14/transcript-obama-biden-endorsement/, there is one Public reply with references `{b188f8d6-7e90-11ea-9bfd-f7625358f743}`. This annotation doesn't exist. This may be the cause of the "a neverending series of requests to the `/api/search` endpoint."

https://hypothes-is.slack.com/archives/C2BLQDKHA/p1587142520246400

**To Reproduce**
1. Go to https://www.washingtonpost.com/politics/2020/04/14/transcript-obama-biden-endorsement/ and open the Sidebar
2. Open the Public group
3. See error - the sidebar loads continuously.

**Expected behavior**
Unclear!

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/79600845-ce7dac80-80b5-11ea-8bb9-a4769d3dc6dc.png)

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10
 - Browser Chrome 81

**Comment by mkdir-washington-edu** [comment]
Per https://github.com/hypothesis/support/issues/111#issuecomment-655600379, this issue seems to have been fixed by the recent changes in how the client searches/loads.

**Comment by klemay** [comment]
Closing since this has been fixed
