### ISSUE TITLE
The Sidebar never finishes loading in an LMS assignment

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#111]
**Describe the bug**
When loading a particular Moodle assignment the Sidebar keeps loading https://hypothes.is/api/search?.... The existing and available annotations and replies never load.

**To Reproduce**
1. Log into the Moodle teacher account ([LMS instances here](https://docs.google.com/document/d/1p7XiZclKWDlkOxlcuHXdkrsGtemGeR5gQiJ4qUq7o00/edit?usp=sharing))
2. Go to the course "Support 101", assignment "Demo"
3. Open the Dev tools, network tab, and refresh the page.

**Expected behavior**
The undeleted, shared annotations should load, and we shouldn't keep loading the api/search call.

**Actual behavior**
 the Sidebar never loads, we keep calling the search API over and over again.

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/81726000-a97e1e80-9454-11ea-93e9-6e99c0d31b0b.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10
 - Chrome 81

**Additional context**
You can see the annotations that should appear here:

```
SELECT *
FROM  "annotation"
WHERE
    document_id = '902131'
   AND groupid = 'xZr8oKvV'
```

May be related to: https://github.com/hypothesis/support/issues/103

So far I've only managed to make this happen on this Moodle assignment and haven't reproduced elsewhere.

**Comment by klemay** [comment]
Questions we'd want to answer before bringing this to engineers:

- How did you discover this issue? Did a user report something in their Moodle instance and you replicated?
- What is the document being annotated in this assignment? Could you provide the URL or attach the PDF?
- Does this affect other assignments, or just this one? (i.e., happens with PDFs but not HTML pages; happens only with this Moodle assignment, happens with all Moodle assignments)

**Comment by mkdir-washington-edu** [comment]
> How did you discover this issue? Did a user report something in their Moodle instance and you replicated?
I had seen this happen before, but I can't find any record of it. I'm not sure if I didn't record it, was waiting to replicate it, or what happened.

I created this issue this morning when I was trying to prep for a short video displaying the refresh/update icon in the Sidebar, as well as the LMS grading functionality in Moodle. I created the Demo assignment and had deleted an annotation when the Sidebar stopped loading.


> What is the document being annotated in this assignment? Could you provide the URL or attach the PDF?

Attached.
[uc (4).pdf](https://github.com/hypothesis/support/files/4617660/uc.4.pdf)


> Does this affect other assignments, or just this one? (i.e., happens with PDFs but not HTML pages; happens only with this Moodle assignment, happens with all Moodle assignments)

I've only managed to make this happen on this Moodle assignment. But thanks for this, because it helped me remember the first issue I wrote where this is happening. [Here's the Slack thread](https://hypothes-is.slack.com/archives/C2BLQDKHA/p1587142520246400), and [here's the ticket](https://github.com/hypothesis/support/issues/103).

**Comment by klemay** [comment]
@mkdir-washington-edu : I had a hunch that perhaps our recent changes to the way the client fetches annotations may have fixed this. Now when I open the assignment you mention in your issue, the sidebar _does_ load for me. Can we close this issue?

**Comment by mkdir-washington-edu** [comment]
@klemay You're right, the problem seems to be fixed. Same for https://github.com/hypothesis/support/issues/103. I'll note this there as well.

**Comment by klemay** [comment]
Thanks @mkdir-washington-edu ! I will close this issue and take it out of the queue!
