### ISSUE TITLE
The Chrome extension, Bookmarklet, and Via do not work when viewing web pages in a proxy

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#125]
**Describe the bug**
A user needs to use a proxy server to get around his country's web restrictions. They've tried the chrome extension, the bookmarklet, and Via, and nothing works. There are some different error messages, depending on what is being tried.

The user sent several messages; I've tried to account for all the different ways they've said things failed.

1.
When trying to log into the Chrome extension, the user gets the message "Error: Fetching https://hypothes.is/api/inks" failed".
![image](https://user-images.githubusercontent.com/22603275/87713254-e5e13a00-c777-11ea-9a41-5567d63a6dda.png)

2.
When logging into the Hypothesis website, they get redirected to a Cloudflare Captcha which doesn't let them progress. When the proxy is on, the the extension does not treat the user as logged in. When they try to login, it sends a request to https://hypothes.is/api/profile, which gives a 403 and they end up with Cloudflare's CAPTCHA.

3.
When they visit https://via.hypothes.is with the proxy, Cloudflare Captcha challenges them.

4.
Trying the Bookmarklet with proxy on fails. According to Chrome devtools, a request to https://cdn.hypothes.is/hypothesis failed with HTTP 403.

**To Reproduce**
I'm uncertain how to reproduce without a proxy server.

**Expected behavior**
The user would like one of the three methods of accessing Hypothesis to work with his proxy server.

**Additional context**
https://hypothesis.zendesk.com/agent/tickets/11318

**Comment by robertknight** [comment]
> When logging into the Hypothesis website, they get redirected to a Cloudflare Captcha which doesn't let them progress.

Did they say what happens if they try to complete the captcha? Also, did they explain who the provider of the proxy server is?

**Comment by mkdir-washington-edu** [comment]
The user didn't answer these questions, but says that when going to web.hypothes.is in their proxy they no longer encounter the error, and that the extension works fine now. Closing this issue.
