### ISSUE TITLE
When clicking links in the LMS app, new links opening in Via causes student and instructor confusion

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#133]
**feature request**
A user wants students to be able to click links in a Via assignment and not be blocked from accessing sites that require cookies. The user doesn't expect that the LMS app will persist after clicking the link.

**Expected behavior**
When a user clicks a link the LMS app a **new tab or page** should open **without it being in Via**.

**Additional context**
https://hypothesis.zendesk.com/agent/tickets/13032

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/13173

**Comment by mkdir-washington-edu** [comment]
@klemay Is this issue more viable now that the LMS app uses Via3 and the web app uses Via? The issue would become about Via3 opening links in Via3.

@mattdricker FYI

**Comment by klemay** [comment]
@mkdir-washington-edu yes, I will get this on our queue for the next backlog review!

**Comment by mkdir-washington-edu** [comment]
To clarify, the issue here is that LMS users click on a link (or as we've learned, get redirected, sometimes to the same page) and end up in the web app within Via3. They don't realize they're in the web app so they make a web app account and annotate in Public.

Opening links outside of Via would help signal to them that something's wrong, or at least not make them think they're still in the LMS app b.c Hypothesis has appeared.

**Comment by klemay** [comment]
Closing this as it is being taken care of as part of our work to secure Via. See [discussion in Slack](https://hypothes-is.slack.com/archives/C0C6BDS1H/p1614017032001900) and [this PR](https://github.com/hypothesis/viahtml/pull/82) for details
