### ISSUE TITLE
RealTime updates showing in incorrect group

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#137]
Originally reported as https://github.com/hypothesis/h/issues/6185; possibly related to https://github.com/hypothesis/support/issues/136.

## Summary
When a user creates a new annotation in a group, that annotation appears via RealTime update in _another_ group. The annotation disappears when the page is refreshed. 

## Steps to Reproduce
You need two people to repro this one. 
1. Choose or create two private groups; ensure both testers are a member of Group A but only one tester is a member of Group B. 
2. Visit the same web page - Tester 1 should have Group A and Group B open in 2 different windows. Tester 2 should have the same web page open, with the Hypothesis sidebar scoped to Group A. 
3. Tester 1 makes an annotation in Group B
4. Tester 2 sees the realtime update icon in the Hypothesis sidebar while looking at Group A. Tester 2 can click the icon to see Tester 1's annotation that was just created in Group B.
5. When Tester 2 refreshes the page, the Group B annotation disappears.

## Screenshots $$
The top two annotations were made in the visible group "abc internal testing?"
The last annotation was made in a different group on the same web page. The annotation Card does not contain a group name, I was not able to reply to the annotation (received an error), and the cancel button does not appear under my reply.

<img width="448" alt="Screen Shot 2020-09-08 at 10 20 40 AM" src="https://user-images.githubusercontent.com/22603275/92490859-86276e00-f1bf-11ea-9cbf-1b7f5f78e243.png">

**Comment by robertknight** [comment]
Slack discussion: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1599576154170900

**Comment by robertknight** [comment]
Debugging / investigation thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1599644981197300

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/pull/2525 has been deployed which will _appear_ to fix this issue from the user's point of view. Avoiding updates showing up in the wrong group depends both on server-side filtering (checking whether the user has _permission_ to see an update) and client-side filtering (checking whether the user has selected the group that the update refers to). The client-side part is now fixed.
