### ISSUE TITLE
How to save PDF annotations?

### ISSUE THREAD

**Issue by tmabraham** [hypothesis/support#140]
I would like to save a PDF with the annotations I had made on them. Is this possible? If not, would there be an easy way to do this with the API? I am new to Hypothesis API so please point me to the best resources. Thanks!

**Comment by klemay** [comment]
Hi @tmabraham - sorry we're just now seeing this. The best way to get help with Hypothesis is to email support@hypothes.is - we use Github for tracking bugs and feature work, so support questions like this one get lost sometimes. 

There isn't a way to print a PDF with the annotations - we have an existing feature request for that here: https://github.com/hypothesis/product-backlog/issues/21
