### ISSUE TITLE
Hypothesis not supporting Markdown's strikethrough

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#141]
**Describe the bug**
Adding "~~" before and after text does not product a strikethrough in Hypothesis. Our [Markdown guide](https://web.hypothes.is/help/formatting-annotations-with-markdown/) specifies that we do this.

**To Reproduce**
1. Create an annotation
2. Use the text "~~This text has been struck through~~"
3. Post the annotation

**Expected behavior**
Using the steps above you should see the whole phrase with a strikethrough.

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/93637148-17b68d00-f9c3-11ea-8d94-8f39a84f7e0d.png)
![image](https://user-images.githubusercontent.com/22603275/93637158-1e450480-f9c3-11ea-9c7e-ce68b68858d4.png)

**Desktop (please complete the following information):**
 - Chrome 95

**Comment by mattdricker** [comment]
Another user reported this issue: https://app.hubspot.com/contacts/6291320/ticket/277766689/

**Comment by robertknight** [comment]
The client currently uses [Showdown](https://github.com/showdownjs/showdown) for markdown rendering. In that implementation, strikethrough support is an [option](https://github.com/showdownjs/showdown#valid-options) which is disabled by default.
