### ISSUE TITLE
ToS incorrectly says deleting accounts does not delete public top-level annotations with replies

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#158]
**Describe the bug**
Our [ToS](https://web.hypothes.is/terms-of-service/), under “Account Termination/Deletion”, says:

> If you have contributed to public conversations that others have replied to we will not delete your individual annotations.

Robert points out this is not the case, the following code does not look for replies to the annotation: https://github.com/hypothesis/h/blob/411f5f31f1cf56f61e14f5f7aaf9583ac1135982/h/services/delete_user.py#L9

**To Reproduce**
1. Create a new temporary account
2. Leave a public annotation
3. Reply to it from another account
4. Delete temporary account
5. Annotation has been deleted.

**Expected behavior**
The ToS and the code will match. At this time Robert recommends changing the ToS to match.

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14
 - Chrome 86

**Additional context**
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1604932034255600

**Comment by xolotl** [comment]
I have created a PR to address this issue. Note that once the PR has been merged, there is still another step that I will do to reflect the changes on the H. website.

**Comment by xolotl** [comment]
@klemay I notice this issue is not assigned to anyone and perhaps not in a sprint. Is it/will it be part of some more official process, or should I just take all the steps with no further adult supervision?

**Comment by klemay** [comment]
@xolotl please do take this one to the finish line! I don't think engineering needs to be involved since we're not making changes to the code in the product.

**Comment by xolotl** [comment]
Sigh, this disappeared of my radar, but now the change already made to the ToS in the repository is also live on the website.
