### ISSUE TITLE
Options for better handling of course sections in LMS app

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/support#168]
Currently Hypothesis only works with Canvas sections, but the concepts in this issue can be thought of in the general with how sections are used by instructors across all LMSes.

The concern was raised by an instructor whose course contains 53 students. They plan on splitting the course into 3 study groups, but the membership of the groups will be shuffled periodically so that students get to work with different people throughout the term.

Here are the requirements and outcomes the instructor described:

- Students should not have to choose which group to annotate into when working in an assignment
- Students should not see any annotations from previous sections they did not belong to
- Students should be able to view their work on previous assignments, even after section membership has shuffled
- Different articles may be assigned to different sections at different times, and the same articles assigned to other sections at other times (in Canvas, possibly taking advantage of the ability to target assignment groups)

**Comment by mattdricker** [comment]
The concern about only one group available for students in an assignment, and thus avoiding them mistakingly annotating in the wrong group, is one that has been brought up several time in multiple tickets.

A common scenario is there will be one organizational section that all class members belong to, then several smaller study groups. Because all students always belong to the "everyone" section, there is never a time where they are presented only one group to annotate into.

**Comment by mattdricker** [comment]
Tickets which borne this issue:

- https://app.hubspot.com/contacts/6291320/ticket/242517174/
- https://app.hubspot.com/contacts/6291320/ticket/280942228/
- https://app.hubspot.com/contacts/6291320/ticket/277888290/

**Comment by klemay** [comment]
Hey @mattdricker thanks for this writeup! Do you see this as fundamentally different from [this existing issue](https://github.com/hypothesis/product-backlog/issues/1151)? 

I fully realize that I asked you to write this one up - mea culpa for not remembering that we already have a similar issue open. Might we link these tickets on [product-backlog/#1151](https://github.com/hypothesis/product-backlog/issues/1151) and close this one?

**Comment by mattdricker** [comment]
Hey @klemay I think both issues are talking around the same concerns! Thanks for remembering the previous issue. Feel free to link and close this in whichever way makes the most sense.

I do think it's important to keep note of the additional details called out by the instructors that are causing the discomfort; specifically not requiring the students to have to choose a group from the dropdown.

**Comment by klemay** [comment]
@mattdricker I've added the ticket links and the point about not using the groups dropdown to the original issue and will close this one. If you feel anything is missing on the other issue, please feel free to add a comment or let me know directly!
