### ISSUE TITLE
Via error messages in the LMS app should not contain language about using the Chrome extension or other web app methods

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#176]
Please kill this if this work is already part of another issue.

**Describe the bug**
Right now when you try to visit a blocklisted page in Via you get an error message directing you to use the Chrome extension. This message shows up in the LMS app when you try to use a blocklisted page there.

Many users are already confused about the difference between the apps. Seeing this error messaeg may lead to LMS users installing the web app and using it over LMS content.

<img width="1114" alt="Screen Shot 2021-03-06 at 11 16 51 AM" src="https://user-images.githubusercontent.com/22603275/110213442-12180b00-7e6e-11eb-8071-484555c02c0f.png">

**To Reproduce**
1. Create a Canvas assignment using a site like https://docdrop.org/video/kt93DVdgtuQ/ (https://hypothesis.instructure.com/courses/92/assignments/1545)
2. See error message

**Expected behavior**
A message explaining the site is blocked, but **not** pointing users towards the web app (Chrome extension, Bookmarklet, etc) would be fine.

**Comment by klemay** [comment]
closing as this is covered by https://github.com/hypothesis/checkmate/issues/118
