### ISSUE TITLE
Allow Hypothesis admins to turn off the LMS app for a given LMS domain

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#180]
**Describe the feature**
Right now Hypothesis is only allowed to be trialed by individual users for one term with a max of 50 students. We have been flexible with this, allowing advocates at institutions where we haven't made headway to continue using Hypothesis. We should be able to keep this option at our discretion.

Other institutions, however, have continued to use us without permission well after their trial is over. Others have declined a pilot or had a pilot and decided to not subscribe to the LMS app, but continue to allow their users to use the LMS app. Eventually we will need a way to turn off the LMS app for a domain if we want to pressure those institutions with active users who are violating our terms.

**Feature behavior**
This feature should allow a Hypothesis admin to enter an LMS URL which will block access to the LMS app when used at that URL. We should tie it to a Consumer Key as the institution can just generate a new Key at will. Blocking access means blocking:
1. The ability to choose PDFs from an LMS file system (like the Canvas picker)
2. The ability to choose PDFs from a non-LMS file system (like Google Drive)
3. The ability to use URLs assignment (which normally function even if the Hypothesis Key and Secret were made for the wrong LMS URL, unlike the other two options). It's possible this last will be too difficult a lift, in which case the former two points may be enough.

In the best case scenario this would also come with an error message explaining that an institution does not have (or no longer has) a paid subscription to the LMS service, and an email link to Sales to strike up a conversation.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/private-issues/issues/49
