### ISSUE TITLE
Spike: Moodle assignment opening in a new window is bypassing the interstitial page that contains the activity description

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#183]
**Describe the bug**
When creating an assignment in Moodle you can choose a "launch container". The applicable choices seem to be "embed" or 
"new window". Assignments can also contain an "activity description" which allows the instructor to add instructions to the assignment.

When editing an assignment with an activity description if you click "save and display" you will be taken to an interstitial page that contains the activity description and a link to open the text in a new window. However, if you click on the link to the assignment from the course page you are taken directly to the text bypassing any instructions the instructor left in the activity description.

Like https://github.com/hypothesis/support/issues/182 this may be a general Moodle issue. I can find the same circumstances when using the ChemVantage LTI tool I've installed in our Moodle instance.

**To Reproduce**
1. Log in to Moodle as a teacher at https://hypothesisuniversity.moodlecloud.com/login/index.php
2. For steps 3 - 7, instead of creating your own assignment you can [visit the Support 101 course here](https://hypothesisuniversity.moodlecloud.com/course/view.php?id=14) and use the first activity, "Demo".
3. Enter a course; I recommend Support 101
4. Turn editing on
5. Add a activity or resource
6. Select "external tool"
7. Create an assignment - make sure to Select "Hypothesis" in the "preconfigured tool" category, to select "new window" as the launch container, and add some text to the activity description.
8. Choose "Save and display" from the assignment editing page
9. Note you are taken to a page with the activity description and a link to launch the assignment in a new window.
10. Go back to the course page and click on the activity link
11. Note you are taken directly to the document.

**Expected behavior**
It would be expected that clicking the activity from the course page would still take you to the interstitial page with the course instructions.

**Screenshots**
![Screen Shot 2021-03-15 at 1 24 33 PM](https://user-images.githubusercontent.com/22603275/111196472-b0ede700-8593-11eb-9523-a01072a48f69.png)

**Additional context**
There are old, closed tickets from Denver Seminary about this. I can find and link to them if needed.

**Comment by mkdir-washington-edu** [comment]
My original research into this issue is here: https://docs.google.com/document/d/1vx5GN1YGlQ5VfGxnaV2NqpUpmmq0PezCImO7WiDR57E/edit?usp=sharing

**Comment by klemay** [comment]
@mkdir-washington-edu this is indeed a Moodle issue - we can't control the way Moodle chooses to launch assignments that are set to open in a new window. Compare the Moodle experience to this assignment in Canvas: https://hypothesis.instructure.com/courses/90/assignments/527?module_item_id=962

Launching from the course page will always show this screen with instructions. This is something we or Denver Seminary would need to take up with Moodle. Going to close this issue since we can't do anything from an eng standpoint.
