### ISSUE TITLE
Spike: When activity text contains the name of another activity Moodle embeds a link to that activity automatically

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#184]
**Describe the bug**
When you create activity text as part of a Hypothesis activity, and if that text matches the names of activities in that course, Moodle embeds links to those other activities within the activity text.

Like #182 this may be a general Moodle issue. I can find the same circumstances when creating native Moodle activities in our Moodle instance.

**To Reproduce**
1. Log in to Moodle as a teacher at https://hypothesisuniversity.moodlecloud.com/login/index.php
2. For steps 3 - 7, instead of creating your own assignment you can visit the Support 101 course here and use this Hypothesis-enabled activity: https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=323
3. Enter a course; I recommend Support 101
4. Turn editing on
5. Add an activity or resource
6. Select "external tool"
7. Create an assignment - make sure to Select "Hypothesis" in the "preconfigured tool" category and add some text to the activity description that matches the titles of other activities (like "Demo", "test", etc).
8. After saving note that the activity text now contains links to assignments that you did not add yourself.

**Expected behavior**
The expectation would be that Moodle only adds links to activity texts when specified by the user.

**Additional context**
There are old, closed tickets from Denver Seminary about this. I can find and link to them if needed.

**Comment by mkdir-washington-edu** [comment]
My original research into this issue is here: https://docs.google.com/document/d/1LivDIzoJJ5Bh8OMpemFIRepCPYMi-dttFRbF8h4lZxI/edit?usp=sharing

**Comment by klemay** [comment]
@mkdir-washington-edu this is also not something we can do anything about - we don't get any info from Moodle re: the assignment descriptions nor do we format/populate that description in any way. This would be something Moodle would have to fix
