### ISSUE TITLE
Turn *off* Sections for Missouri Baptist U

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#197]
Consumer Key: Hypothesisdf38fbf93e5b970cb109948c344d5be5

Ticket: https://app.hubspot.com/contacts/6291320/ticket/390573487/
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1619553384270000

This U wants Sections turned off for the upcoming semester so courses that have not launched Hypothesis yet won't end up with Sections access. Please feel free to sent any questions my way!

**Comment by mkdir-washington-edu** [comment]
@seanh ^

**Comment by seanh** [comment]
Done
