### ISSUE TITLE
Remove link to Via request form from https://via.hypothes.is

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#200]
**Describe the bug**
Our Via request form is for sites not currently on the allow list. You can find a link to that form on the page you see when a site is not on the allow list:
![image](https://user-images.githubusercontent.com/22603275/117583779-17483f00-b0d7-11eb-9ab0-49e534fbb246.png)

It also appears on our abuse page and other sites. It **also** appears on via.hypothes.is, and it appears that this is confusing some users. We're seeing an increasing number of folks who are creating Via allow requests for sites that are allowed in Via.

This may be users not checking, but in some cases it seems to be because the site blocks appearing in a proxy, but the user believes it's Via blocking the content on the site from appearing.

**To Reproduce**
No steps to reproduce.

**Expected behavior**
We should keep the Via allow form on the page that shows up when a site is **not** on the allow list, and keep it on our abuse page.

We should **remove** the link to the form from Via.hypothes.is, since that's the most likely place users are accessing the form after a site successfully loads in Via.

**Comment by mattdricker** [comment]
Change made per https://github.com/hypothesis/via/pull/515

Closing.
