### ISSUE TITLE
metrics: use Zendesk API to pull avg and median time to resolve ticket each month

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#22]
Zendesk's API endpoints for Ticket metrics: https://developer.zendesk.com/rest_api/docs/core/ticket_metrics 

In particular, we may want:
- `id`  (ticket ID)
- `created_at`
- `solved_at`

These also could be interesting: 	
- `replies`  (total # of times ticket was replied to)
- `first_resolution_time_in_minutes` 
- `full_resolution_time_in_minutes`

At the end of every month, we'll need to:

- Get all of the tickets created that month, along with the stats listed above
- Find the median and average for `first_resolution_time_in_minutes` and `full_resolution_time_in_minutes`

Since I'm using Zapier to pull ticket IDs and tags, I wonder if these hooks are available through Zapier. I could just have the spreadsheet populate this additional data and wouldn't have to interact with the Zendesk API at all :)

**Comment by lyzadanger** [comment]
I wonder if median could be a handy stat, too, as averages could get skewed (maybe?) by some tickets that are open a _real_ long time?

**Comment by klemay** [comment]
Good call! changing ticket title!

**Comment by klemay** [comment]
Ah, unfortunately Zapier won't let me pull `solved_at` so this will require working directly with the Zendesk API. Might need to icebox this for the time being.

**Comment by klemay** [comment]
Somehow, I missed this during my first round of research: https://developer.zendesk.com/rest_api/docs/core/ticket_metrics

This gives us, among other data points:  

`first_resolution_time_in_minutes`
`full_resolution_time_in_minutes`

I think the median and average for both figures would be work looking at. I was able to get tickets dating back to April 5, 2018. The API doesn't allow access to metrics for archived tickets, so historical data will be another research project. 

To get this data:

- Create an API token for Zendesk here: https://hypothesis.zendesk.com/agent/admin/api/settings
- Use an API dev environment to access https://hypothesis.zendesk.com/api/v2/ticket_metrics.json?page=1 (changing the `page` query to get results further in the past)
- Use `Basic Auth` for your authentication type
- The `Username` is the email address associated with your Zendesk account with /token at the end, e.g. `katelyn@hypothes.is/token`
- The `Password` will be the Zendesk API key you generated

I used Postman, and my request looked like this:

<img width="980" alt="screen shot 2018-08-21 at 2 33 15 pm" src="https://user-images.githubusercontent.com/12087705/44421655-32517a00-a54f-11e8-807a-0c761ebe37fd.png">

I then took the JSON output and converted it to CSV using this tool: https://json-csv.com/

Steps for working with the data & calculating resolution times still to come. :)

**Comment by klemay** [comment]
As it turns out, `first_resolution_time_in_minutes` and `full_resolution_time_in_minutes` are not among the ticket metrics Zapier can pull. I've submitted a feature request, but in the meantime we'll need to manually pull this data every month.

**Comment by klemay** [comment]
Notes on progress:

- We have [metrics going back to May 2018](https://docs.google.com/spreadsheets/d/1k_8ozGO9o2LalDZjIMQxoUsgl5hhCZbqtjm_oy_p2iQ/edit#gid=0), because tickets older than that are archived. Zendesk does not provide access to metrics on archived tickets (even through the API!) unless you pay for a Professional or Enterprise account (we have a Team account). 
- For all future months, store JSON output [here](https://drive.google.com/drive/folders/1fT2aTJlLfJwv6hz66ThFY63NO1gUT4HV) so we don't lose access to this data as the tickets become archived. 
- I will be calculating metrics for August this week and will document the process at that time.

**Comment by klemay** [comment]
Done!
