### ISSUE TITLE
Turn on OneDrive for all LMS installs

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#232]
Once we've determined what done looks like for the MS OneDrive integration with the LMS app we need to decide on a date and time to turn this on. This needs to be coordinated with:
- Support: The release of new OneDrive KB articles and edits to all existing assignment creation articles to include the OneDrive option.
- Product: Emailing LMS app users to let them know the option is about to be available.

**Comment by chrisshaw** [comment]
# QA Testing errors

- [ ] Public links in shared Libraries are not supported
  - Expected: When I select a file in a shared library, it gets assigned
  - Actual: I get an error:
![image](https://user-images.githubusercontent.com/2966918/140820751-cb0fffab-2642-4a98-b220-9b1268193737.png)
  - Steps to reproduce

https://user-images.githubusercontent.com/2966918/140820481-98e02c68-78a3-480f-b9a1-bfbe3bcd2377.mp4

**Comment by marcospri** [comment]
Done on https://github.com/hypothesis/lms/pull/3388
