### ISSUE TITLE
Article: annotating content on pages with Hypothesis embedded

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#24]
Based on: http://help.osf.io/m/preprints/l/933230-annotate-a-preprint

**Comment by dwhly** [comment]
Also, concerns this: https://github.com/hypothesis/product-backlog/issues/720

**Comment by klemay** [comment]
I think this is covered by @xolotl's Annotation Basics: https://web.hypothes.is/help/annotation-basics/

Thanks for helping to close out one of the KB backlog items!
