### ISSUE TITLE
[Bug] Annotation.uri: localhost:4000

### ISSUE THREAD

**Issue by kael** [hypothesis/support#255]
**Describe the bug**

Bookmarking https://inkdroid.org/2016/04/14/warc-work/ created an annotation with an `annotation.uri` and `annotation.target[0].source` pointing to `http://localhost:4000/2016/04/14/warc-work/`

**To Reproduce**

Annotations:
* JSON
  - https://api.hypothes.is/api/annotations/e0bwvGjGEey43CNw1DScZw
  - https://api.hypothes.is/api/annotations/rMaYSmjGEey1HM9rTM_x3w
* HTML (pointing to localhost:4000)
  - https://hyp.is/e0bwvGjGEey43CNw1DScZw/localhost:4000/2016/04/14/warc-work/

**Comment by mkdir-washington-edu** [comment]
@kael 
That URL contains:
><link rel="canonical" href="http://localhost:4000/2016/04/14/warc-work/">

Hypothesis respects rel="canonical". Please see [these](https://web.hypothes.is/help/how-hypothesis-interacts-with-document-metadata/) [two](https://web.hypothes.is/help/how-to-establish-or-avoid-document-equivalence-in-the-hypothesis-system/) articles. In short, the presence of rel="canonical" on that page means annotations will be associated with the canonical URL.

**Comment by edsu** [comment]
Thanks for noticing the problem with my site!
