### ISSUE TITLE
[support] Inform users of search_after parameter

### ISSUE THREAD

**Issue by klemay** [hypothesis/support#43]
Previously, Hypothesis searched for bulk annotations by a sliding window where the `/api/search` endpoint would return `limit` number of annotations starting at `offset`. Newer versions of elasticsearch impose a limit on `offset` and `limit` which means it's no longer possible to return any annotations beyond the 10,000th annotation by using `offset` and `limit`.

As a result, `search_after` is the new standard in Hypothesis to search for large numbers of annotations. We recommend that users change any requests to the `/api/search` endpoint that currently use `offset` to page through large numbers of annotations to use `search_after` instead. 

Hannah has [updated our API documentation](https://h.readthedocs.io/en/latest/api-reference/#operation/search) to include instructions for using `search_after`, and has written up an explainer that goes over how it works and why to use it in more detail:

https://docs.google.com/document/d/13o825FC14G3NT61OSseCXf-hM_vDvTsl5pRKlH5x3rI/edit?ts=5bdcd29b

We'd like to reach users to who are working with our API to let them know about this. I'm not sure of the best way to go about this, so I'm calling in @xolotl and his Marketing superpowers!

Here's what I'm thinking:
- Turn Hannah's Google doc into a blog post + KB article (like we did for wildcard search)
- Post a link (to the blog post? to the KB article?) to our [h-dev] forum, Twitter, and public Slack channels
- Consult with @judell to see if he knows of anyone we should reach out to directly regarding this

Questions for Nate:
- Do you feel a blog post is appropriate, or should we stick to a KB article?
- Are there any email lists you think this should go out to?
- Are there any other communication channels I'm forgetting? 
- Should I create a Trello card / track this in some other way that will be more helpful to you?

**Comment by xolotl** [comment]
I think the common pattern we should follow for all such things is to first focus on getting the right info in the right documentation places (ie, help and/or docs) — just like we did with domain search. This is the most important part. Second focus: how/if to promote more widely, pointing to such docs.

In cases where the capability/change is of substantial use/interest to our audiences, we should promote it and its documentation with something like the following: blog post/social/email when the innovation is more highly compelling; social media when the innovation is less compelling.

Given our resources at H: the promotion of such innovations can only happen if it's a group effort. So jointly we might figure out a strategy for an innovation, and then it will take several folks to make it happen, including both the documentation and the promotion steps.

Based on my limited understanding of this specific change, it seems to me not to be of super high interest because it is just a technical change in how to make something happen that was already possible. As such, unless there is a more compelling story I'm not seeing, I might recommend a focus on documentation and a promotion via social.

**Comment by xolotl** [comment]
Once a promotion strategy is decided on, indeed it would be helpful to record it with one or more cards on the [Marketing Trello board](https://trello.com/b/Si3A6pqa).

**Comment by judell** [comment]
For starters, https://metabase.hypothes.is/question/438 shows that the top two bulk API users are @tgbugs and @haritzmedina. 

And for what it's worth, it doesn't appear there are other API users who are active enough to be having problems with the `offset` method.

**Comment by tgbugs** [comment]
For the record I have also already updated my client library to [use](https://github.com/tgbugs/hyputils/blob/3056fc7a6194115d1cb506a65eaa8d71ac061d37/hyputils/hypothesis.py#L70) search_after (its great!).

**Comment by judell** [comment]
👍

**Comment by haritzmedina** [comment]
Currently, none of my apps need search for bulk annotations beyond the 10.000th, but I already have started using search_after in some of my [library's tests](https://github.com/haritzmedina/hypothesis-api-client/blob/60e49f9a49383227f065df7965ed380728b2393c/lib/__tests__/hypothesisApiClient.test.js#L39), which is more powerful and reliable. In the following days I will update the [bulk search function](https://github.com/haritzmedina/hypothesis-api-client/blob/60e49f9a49383227f065df7965ed380728b2393c/lib/index.js#L199) in my client to avoid the use of offset param. Thanks for notifying me @judell .

**Comment by klemay** [comment]
> I think the common pattern we should follow for all such things is to first focus on getting the right info in the right documentation places (ie, help and/or docs) — just like we did with domain search. This is the most important part. Second focus: how/if to promote more widely, pointing to such docs.

This has been documented by the engineers here: https://h.readthedocs.io/en/latest/api-reference/#operation/search

> Based on my limited understanding of this specific change, it seems to me not to be of super high interest because it is just a technical change in how to make something happen that was already possible. 

This is high interest because this new parameter has made it _significantly_ more efficient to search for large #s of annotations (and if people try to use our old parameter to do this, they won't be able to). The implications for researchers and for us as part of the open source community make an interesting story IMO

Given the two points addressed above, I would suggest:

- [ ] Blog post linking to readthedocs 
- [ ] Share blog post to h-dev mailing list, public Slack, and Twitter

**Comment by ajpeddakotla** [comment]
Let's do a blog post so we can link to it and share it out on the appropriate lists. I think the devs should be able to do this (write a blog post that is more dev-specific) when there's comms that need to be made like this.

**Comment by xolotl** [comment]
Based on @klemay's description of this change I agree: sounds totally blogworthy and promotable, and that post obviously should point to any related documentation whereever it lives.

I'll put a card in the marketing backlog to represent this post and add @ajpeddakotla so she can keep it updated with a target publication date, links to drafts, etc.

**Comment by klemay** [comment]
Thanks Nate! I told Arti I'd take this on, so I'll look out for the card and add myself!

**Comment by xolotl** [comment]
@klemay feel free to set a due date to the card and move it to a week column
https://trello.com/c/G9TvguoM

**Comment by klemay** [comment]
Thanks to Nate for creating the Trello card - will be tracking progress here: https://trello.com/c/G9TvguoM

**Comment by klemay** [comment]
@hmstepanek the post is live here: https://web.hypothes.is/blog/new-search-api-parameter-search_after/
