### ISSUE TITLE
Medium borks H icons when using bookmarklet

### ISSUE THREAD

**Issue by xolotl** [hypothesis/support#44]
It looks like Medium may be blocking icons used in the H client with the bookmarklet (visiting https://hackernoon.com/decentralizing-everything-never-seems-to-work-2bb0461bd168 in FF 63.0.1 (64-bit) on Mac OS 10.14). Note that this does not seem to be an issue when using the Chrome extension or via.

Here's the console error and a screenshot: "Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.hypothes.is/hypothesis/1.101.0/build/fonts/h.woff (“font-src”)."

![what_to_do_once_you_admit_that_decentralizing_everything_never_seems_to_work_and_inbox__127__-_nateangell_hypothes_is_-_hypothes_is_project_mail](https://user-images.githubusercontent.com/997548/48089415-4c4b4200-e1b9-11e8-9c38-c6e55bb697f8.png)

**Comment by klemay** [comment]
This is an example of the problem described by https://github.com/hypothesis/client/issues/244, which has been added to our backlog & prioritized. I'm going to close this issue, but I have linked to it in 244 as an example that can be checked when we start to test/deploy a solution.
