### ISSUE TITLE
Via fails to load https://edtechbooks.org/k12blended/blendedteachingfoundations/simple

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#83]
When visiting https://edtechbooks.org/k12blended/blendedteachingfoundations/simple, you get the error:
> Pywb Error
> Could not load the url from the live web: https://edtechbooks.org/k12blended/blendedteachingfoundations/simple

Hannah saw the same error when visiting https://qa-via.hypothes.is/https://edtechbooks.org/k12blended/blendedteachingfoundations/simple.

The following error was seen locally by Hannah and in Via by Robert:
> web                  | SSLError: HTTPSConnectionPool(host='edtechbooks.org', port=443): Max retries exceeded with url: /k12blended/blendedteachingfoundations/simple (C
> aused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by robertknight** [comment]
I can reproduce the issue in the Python REPL:

```
[I] (via)  ~/h/r/via > .tox/dev/bin/python
Python 2.7.16 (default, Dec 12 2019, 17:23:12)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://edtechbooks.org/k12blended/blendedteachingfoundations/simple')
```

The same thing happens when attempting the above from the lms repo where we are using Python 3 and current versions of the `requests` and `certifi` packages:

```
[I] (h-lms)  ~/h/r/lms > .tox/py36-dev/bin/python
Python 3.6.9 (default, Aug 15 2019, 16:28:48)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
>>> import requests
>>> requests.get("https://edtechbooks.org/k12blended/blendedteachingfoundations/simple")
Traceback (most recent call last):
  File "/Users/robert/hypothesis/repos/lms/.tox/py36-dev/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Users/robert/hypothesis/repos/lms/.tox/py36-dev/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Users/robert/hypothesis/repos/lms/.tox/py36-dev/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Users/robert/hypothesis/repos/lms/.tox/py36-dev/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/Users/robert/hypothesis/repos/lms/.tox/py36-dev/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/robert/.pyenv/versions/3.6.9/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Users/robert/.pyenv/versions/3.6.9/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/Users/robert/.pyenv/versions/3.6.9/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/robert/.pyenv/versions/3.6.9/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
```

**Comment by robertknight** [comment]
I changed the title because the site isn't blocking Via, it is Via that is failing to accept the SSL certificate that the site presents.

**Comment by klemay** [comment]
@robertknight or @hmstepanek could you help us understand what needs to be done here? i.e., is this something we fix in Via, or do we need to contact the site owners and ask them to update their SSL certificate?

**Comment by hmstepanek** [comment]
My understanding is it's our SSL certificate that needs updating but I can't be 100% certain until someone looks into it in more detail. I was hoping to take a look at this next week if it can wait till then.

**Comment by klemay** [comment]
Thanks, Hannah! Yes, this can definitely wait until next week - just wanted to make sure I understood what was going on here!

**Comment by hmstepanek** [comment]
Ok didn't see Rob's comment till just now and I also ran that url against an SSL certificate checker and it looks like there is a problem with their certificate: https://www.sslshopper.com/ssl-checker.html#hostname=https://edtechbooks.org/k12blended/blendedteachingfoundations/simple. So in that case, it does appear this is not an issue with via but rather an issue with the third party's certificate.

**Comment by mkdir-washington-edu** [comment]
Ok, I'll ask the partner about updating their SSL certificate, and I'll post back here with the results. Thanks!

**Comment by mkdir-washington-edu** [comment]
Ok! The site loads, but very, very, very slow (about 1 minute). @hmstepanek if you're still free next week to check if the slowness is something on our end, that would be great.

**Comment by klemay** [comment]
@mkdir-washington-edu I just tested this out, and it now loads instantly for me when I use Via (for Chrome, FF, and Safari on Mac). Can we close this issue?

**Comment by mkdir-washington-edu** [comment]
@klemay Yeah, sorry for the delay, we can close the issue.
