### ISSUE TITLE
Intermittently, when attempting to select text that has already been highlighted, the selection doesn't follow the cursor

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#92]
**Describe the bug**
When you attempt to click and drag to select text, and the selection goes over an area that is already highlighted, the selection will jump around and not follow the cursor until you are several words past the old highlight.

**To Reproduce**
1. Go to any URL, such as https://www.npr.org/sections/health-shots/2020/02/27/809936132/cdc-fixes-issue-delaying-coronavirus-testing-in-u-s
2. Select a single word and select "Highlight" Adder.
3. Start highlighting on an earlier word and attempt to highlight over and past the Highloght you created in step 2.

I was able to replicate this in the wild, in the LMS app, on PDFs, and on web pages.

**Expected behavior**
The selection should follow the cursor, even when it overlaps with the old highlight.

**Screenshots**
Although the cursor is not visible, see video here: https://drive.google.com/file/d/1AQINpmc28katXvlK78STwoTMUe2bP9_m/view

**Desktop (please complete the following information):**
 - iOS
 - Chrome 80

**Additional context**
Slightly different behavior in Firefox 73.0.1. Instead of jumping around, the selecting highlight simply stops moving, not following the cursor, until it jumps back into place several words later.

Lyza has checked and this is not related to her recent work on how highlights are saved.

https://hypothesis.zendesk.com/agent/tickets/8561

**Comment by klemay** [comment]
@robertknight is this by any chance related to recent work re: accessibility for highlights? (If the answer is not an easy "yes," this can be prioritized via bug backlog - just checking before sending this one to the backlog).

**Comment by robertknight** [comment]
> @robertknight is this by any chance related to recent work re: accessibility for highlights? 

Yes, I think so. It looks like the hidden text added before and after the highlighted content using CSS `::before` and `::after` pseudo-selectors can interfere with the browser's text selection behaviour.
