### ISSUE TITLE
Sidebar doesn't render correctly when using Via with IE 11

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#94]
**Describe the bug**
When using Via in IE 11, the top portion of the Sidebar (containing the search, sort, and log in icons) does not display correctly. The sort icon is on its own line under search, the share and help icons are on a line under sort, and the Sign up/Log in links are on a line under that (see attached).

**To Reproduce**
1. Open IE 11 on Win 10
2. Go to via.hypothes.is/https://www.theatlantic.com

**Expected behavior**
The top row of icons and links (search, sort, share, help, sign in) should all appear in the same row.

**Screenshots**
![IE atlantic](https://user-images.githubusercontent.com/22603275/76242210-ac6a5200-620c-11ea-8769-2b3c3d96303c.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - IE
 - 11

**Comment by klemay** [comment]
Depends on https://github.com/hypothesis/product-backlog/issues/1095
