### ISSUE TITLE
"Saving..." message does not appear in AnnotationOmega on Chrome 80 on Mac

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#95]
**Describe the bug**
When saving an annotation, "Saving..." does not appear on the annotation card.

**To Reproduce**
1. Open Dev Tools and the Network Tab
2. Change "Online" to "Slow 3G"
3. Create an annotation and save it
4. The Card does not display "Saving..." during the saving process.

**Expected behavior**
<img width="878" alt="Screen Shot 2020-03-09 at 4 15 14 PM" src="https://user-images.githubusercontent.com/22603275/76253824-be0a2480-6221-11ea-9560-3ffba5b42c2a.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome
 - 80

**Comment by klemay** [comment]
Note that this is only apparent/occurrent when testing slow speeds.

I was able to replicate this with AnnotationOmega on Chrome for Mac, set to "Slow 3G". My details:

timestamp: Mon Mar 09 2020 16:10:52 GMT-0400 (Eastern Daylight Time)
url: https://en.wikipedia.org/wiki/Outlaw:_The_Saga_of_Gisli
fingerprint: N/A
account: katelyn (acct:klemay@hypothes.is)
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0
version: 1.343.0

![screencast-web hypothes is-2020 02 20-16_06_15](https://user-images.githubusercontent.com/12087705/76254535-0413b800-6223-11ea-9eec-9f6f6dead7ba.gif)

Note that there is a "spinning wheel" at the top of the annotation sidebar - @mkdir-washington-edu are we expecting to see the spinning wheel _and_ "Saving..." at the bottom of the card?

**Comment by mkdir-washington-edu** [comment]
@klemay I see both "Saving..." and a spinning wheel in the non-AnnotationOmega version.
<img width="533" alt="Screen Shot 2020-03-09 at 4 52 15 PM" src="https://user-images.githubusercontent.com/22603275/76256540-818cf780-6226-11ea-803e-49c4728cfa93.png">

**Comment by mkdir-washington-edu** [comment]
This also does **not** appear in Edge 80 (which is Chromium-based).

The "Saving..." phrase **does** appear in Firefox (Mac and Windows) and in Safari 13.

**Comment by mkdir-washington-edu** [comment]
This issue was caused by the extension when it is less than version 1.345. Closing.
