### ISSUE TITLE
When refreshing an LMS assignment, red new/updated annotation button stops working for the other party

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/support#99]
**Describe the bug**
When two parties have an LMS assignment open and party A creates a new annotation, party B shows the red new/updated annotation icon in their Sidebar.

But if party A refreshes their browser and then creates a new annotation, party B **does not** show the red new/updated annotation icon.

**To Reproduce**
1. Log into Canvas as an instructor and open a Canvas LMS assignment (https://hypothesis.instructure.com/courses/98/assignments/777 in Support 103 works)
2. In another Chrome identity or another browser, log into Canvas as a student and open the same assignment
3. Leave a new annotation as an instructor and confirm the red icon appears on the student side.
4. Leave a new annotation as a student and confirm the red icon appears on the instructor side.
5. **Refresh the instructor web browser**, and do not refresh the student web browser.
6. Leave a new annotation as the student and confirm the red icon appears on the instructor side.
7. Leave a new annotation as the instructor and confirm the red icon does **not** appear on the student side.

**Expected behavior**
In step 7 the expected result is that the red icon should appear on the student side, like it has before. However, it does not.

**Video**
https://drive.google.com/file/d/1x5vWg_V0xvhuZFLR08YYOKqopkN6AjWd/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Mac Mojave
 - Browser Chrome 80

**Additional notes**
I can not replicate this in the wild. Used Mac Mojave Chrome 80 on https://www.cnn.com/2020/03/11/health/coronavirus-cold-allergies-flu-difference-symptoms-wellness-trnd/index.html in Public

From:
https://hypothesis.zendesk.com/agent/tickets/9068
https://hypothesis.zendesk.com/agent/tickets/9187

**Comment by mkdir-washington-edu** [comment]
Other tickets:
https://hypothesis.zendesk.com/agent/tickets/9415

**Comment by LMS007** [comment]
After much testing, this seems to be working again, closing this out util it comes up again.
